# Generated by Django 3.2.9 on 2021-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('L', 'Lecturer'), (None, 'Unknown')], default=None, max_length=7, null=True),
        ),
    ]
